// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.counterparty;

public interface CreateCounterPartyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:counterparty.CreateCounterPartyResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.counterparty.CounterParty CounterParty = 1[json_name = "counter_party", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasCounterParty();
  /**
   * <code>.counterparty.CounterParty CounterParty = 1[json_name = "counter_party", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  to.bnk.api.counterparty.CounterParty getCounterParty();

  /**
   * <code>.counterparty.Metadata Metadata = 2[json_name = "metadata", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasMetadata();
  /**
   * <code>.counterparty.Metadata Metadata = 2[json_name = "metadata", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  to.bnk.api.counterparty.Metadata getMetadata();

  /**
   * <code>.types.Location PhysicalLocation = 3[json_name = "physical_location", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasPhysicalLocation();
  /**
   * <code>.types.Location PhysicalLocation = 3[json_name = "physical_location", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  to.bnk.api.types.Location getPhysicalLocation();

  /**
   * <code>string PrivateAlias = 4[json_name = "private_alias", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getPrivateAlias();
  /**
   * <code>string PrivateAlias = 4[json_name = "private_alias", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getPrivateAliasBytes();
}
