// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.branch;

/**
 * Protobuf type {@code branch.GetBranchesResponse}
 */
public  final class GetBranchesResponse extends
    com.google.protobuf.GeneratedMessageLite<
        GetBranchesResponse, GetBranchesResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:branch.GetBranchesResponse)
    GetBranchesResponseOrBuilder {
  private GetBranchesResponse() {
    result_ = emptyProtobufList();
  }
  public static final int RESULT_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<to.bnk.api.branch.Branch> result_;
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.util.List<to.bnk.api.branch.Branch> getResultList() {
    return result_;
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public java.util.List<? extends to.bnk.api.branch.BranchOrBuilder> 
      getResultOrBuilderList() {
    return result_;
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getResultCount() {
    return result_.size();
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.branch.Branch getResult(int index) {
    return result_.get(index);
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public to.bnk.api.branch.BranchOrBuilder getResultOrBuilder(
      int index) {
    return result_.get(index);
  }
  private void ensureResultIsMutable() {
    if (!result_.isModifiable()) {
      result_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(result_);
     }
  }

  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setResult(
      int index, to.bnk.api.branch.Branch value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureResultIsMutable();
    result_.set(index, value);
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setResult(
      int index, to.bnk.api.branch.Branch.Builder builderForValue) {
    ensureResultIsMutable();
    result_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addResult(to.bnk.api.branch.Branch value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureResultIsMutable();
    result_.add(value);
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addResult(
      int index, to.bnk.api.branch.Branch value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureResultIsMutable();
    result_.add(index, value);
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addResult(
      to.bnk.api.branch.Branch.Builder builderForValue) {
    ensureResultIsMutable();
    result_.add(builderForValue.build());
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addResult(
      int index, to.bnk.api.branch.Branch.Builder builderForValue) {
    ensureResultIsMutable();
    result_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAllResult(
      java.lang.Iterable<? extends to.bnk.api.branch.Branch> values) {
    ensureResultIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, result_);
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearResult() {
    result_ = emptyProtobufList();
  }
  /**
   * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void removeResult(int index) {
    ensureResultIsMutable();
    result_.remove(index);
  }

  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.branch.GetBranchesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.branch.GetBranchesResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code branch.GetBranchesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.branch.GetBranchesResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:branch.GetBranchesResponse)
      to.bnk.api.branch.GetBranchesResponseOrBuilder {
    // Construct using to.bnk.api.branch.GetBranchesResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.util.List<to.bnk.api.branch.Branch> getResultList() {
      return java.util.Collections.unmodifiableList(
          instance.getResultList());
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getResultCount() {
      return instance.getResultCount();
    }/**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.branch.Branch getResult(int index) {
      return instance.getResult(index);
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setResult(
        int index, to.bnk.api.branch.Branch value) {
      copyOnWrite();
      instance.setResult(index, value);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setResult(
        int index, to.bnk.api.branch.Branch.Builder builderForValue) {
      copyOnWrite();
      instance.setResult(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addResult(to.bnk.api.branch.Branch value) {
      copyOnWrite();
      instance.addResult(value);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addResult(
        int index, to.bnk.api.branch.Branch value) {
      copyOnWrite();
      instance.addResult(index, value);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addResult(
        to.bnk.api.branch.Branch.Builder builderForValue) {
      copyOnWrite();
      instance.addResult(builderForValue);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addResult(
        int index, to.bnk.api.branch.Branch.Builder builderForValue) {
      copyOnWrite();
      instance.addResult(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAllResult(
        java.lang.Iterable<? extends to.bnk.api.branch.Branch> values) {
      copyOnWrite();
      instance.addAllResult(values);
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }
    /**
     * <code>repeated .branch.Branch Result = 1[json_name = "result", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder removeResult(int index) {
      copyOnWrite();
      instance.removeResult(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:branch.GetBranchesResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.branch.GetBranchesResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            to.bnk.api.branch.Branch.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.branch.GetBranchesResponse> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.branch.GetBranchesResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.branch.GetBranchesResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:branch.GetBranchesResponse)
  private static final to.bnk.api.branch.GetBranchesResponse DEFAULT_INSTANCE;
  static {
    GetBranchesResponse defaultInstance = new GetBranchesResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetBranchesResponse.class, defaultInstance);
  }

  public static to.bnk.api.branch.GetBranchesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetBranchesResponse> PARSER;

  public static com.google.protobuf.Parser<GetBranchesResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

