// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.kyc;

/**
 * Protobuf type {@code kyc.Check}
 */
public  final class Check extends
    com.google.protobuf.GeneratedMessageLite<
        Check, Check.Builder> implements
    // @@protoc_insertion_point(message_implements:kyc.Check)
    CheckOrBuilder {
  private Check() {
    bankID_ = "";
    customerID_ = "";
    iD_ = "";
    customerNumber_ = "";
    how_ = "";
    staffUserID_ = "";
    staffName_ = "";
    comments_ = "";
  }
  public static final int BANKID_FIELD_NUMBER = 1;
  private java.lang.String bankID_;
  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getBankID() {
    return bankID_;
  }
  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBankIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(bankID_);
  }
  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBankID(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    bankID_ = value;
  }
  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearBankID() {
    
    bankID_ = getDefaultInstance().getBankID();
  }
  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBankIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    bankID_ = value.toStringUtf8();
  }

  public static final int CUSTOMERID_FIELD_NUMBER = 2;
  private java.lang.String customerID_;
  /**
   * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getCustomerID() {
    return customerID_;
  }
  /**
   * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(customerID_);
  }
  /**
   * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCustomerID(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    customerID_ = value;
  }
  /**
   * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearCustomerID() {
    
    customerID_ = getDefaultInstance().getCustomerID();
  }
  /**
   * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCustomerIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    customerID_ = value.toStringUtf8();
  }

  public static final int ID_FIELD_NUMBER = 3;
  private java.lang.String iD_;
  /**
   * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getID() {
    return iD_;
  }
  /**
   * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(iD_);
  }
  /**
   * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setID(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    iD_ = value;
  }
  /**
   * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearID() {
    
    iD_ = getDefaultInstance().getID();
  }
  /**
   * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    iD_ = value.toStringUtf8();
  }

  public static final int CUSTOMERNUMBER_FIELD_NUMBER = 4;
  private java.lang.String customerNumber_;
  /**
   * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getCustomerNumber() {
    return customerNumber_;
  }
  /**
   * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerNumberBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(customerNumber_);
  }
  /**
   * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCustomerNumber(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    customerNumber_ = value;
  }
  /**
   * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearCustomerNumber() {
    
    customerNumber_ = getDefaultInstance().getCustomerNumber();
  }
  /**
   * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCustomerNumberBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    customerNumber_ = value.toStringUtf8();
  }

  public static final int DATE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp date_;
  /**
   * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDate() {
    return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDate(com.google.protobuf.Timestamp value) {
    if (value == null) {
      throw new NullPointerException();
    }
    date_ = value;
    
    }
  /**
   * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDate(
      com.google.protobuf.Timestamp.Builder builderForValue) {
    date_ = builderForValue.build();
    
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDate(com.google.protobuf.Timestamp value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (date_ != null &&
        date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      date_ =
        com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
    } else {
      date_ = value;
    }
    
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearDate() {  date_ = null;
    
  }

  public static final int HOW_FIELD_NUMBER = 6;
  private java.lang.String how_;
  /**
   * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getHow() {
    return how_;
  }
  /**
   * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHowBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(how_);
  }
  /**
   * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setHow(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    how_ = value;
  }
  /**
   * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearHow() {
    
    how_ = getDefaultInstance().getHow();
  }
  /**
   * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setHowBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    how_ = value.toStringUtf8();
  }

  public static final int STAFFUSERID_FIELD_NUMBER = 7;
  private java.lang.String staffUserID_;
  /**
   * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getStaffUserID() {
    return staffUserID_;
  }
  /**
   * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStaffUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(staffUserID_);
  }
  /**
   * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setStaffUserID(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    staffUserID_ = value;
  }
  /**
   * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearStaffUserID() {
    
    staffUserID_ = getDefaultInstance().getStaffUserID();
  }
  /**
   * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setStaffUserIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    staffUserID_ = value.toStringUtf8();
  }

  public static final int STAFFNAME_FIELD_NUMBER = 8;
  private java.lang.String staffName_;
  /**
   * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getStaffName() {
    return staffName_;
  }
  /**
   * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStaffNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(staffName_);
  }
  /**
   * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setStaffName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    staffName_ = value;
  }
  /**
   * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearStaffName() {
    
    staffName_ = getDefaultInstance().getStaffName();
  }
  /**
   * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setStaffNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    staffName_ = value.toStringUtf8();
  }

  public static final int SATISFIED_FIELD_NUMBER = 9;
  private boolean satisfied_;
  /**
   * <code>bool Satisfied = 9[json_name = "satisfied", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean getSatisfied() {
    return satisfied_;
  }
  /**
   * <code>bool Satisfied = 9[json_name = "satisfied", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setSatisfied(boolean value) {
    
    satisfied_ = value;
  }
  /**
   * <code>bool Satisfied = 9[json_name = "satisfied", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearSatisfied() {
    
    satisfied_ = false;
  }

  public static final int COMMENTS_FIELD_NUMBER = 10;
  private java.lang.String comments_;
  /**
   * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getComments() {
    return comments_;
  }
  /**
   * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(comments_);
  }
  /**
   * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setComments(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    comments_ = value;
  }
  /**
   * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearComments() {
    
    comments_ = getDefaultInstance().getComments();
  }
  /**
   * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCommentsBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    comments_ = value.toStringUtf8();
  }

  public static to.bnk.api.kyc.Check parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.kyc.Check parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.kyc.Check parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.kyc.Check parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.kyc.Check parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.kyc.Check parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.kyc.Check prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code kyc.Check}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.kyc.Check, Builder> implements
      // @@protoc_insertion_point(builder_implements:kyc.Check)
      to.bnk.api.kyc.CheckOrBuilder {
    // Construct using to.bnk.api.kyc.Check.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getBankID() {
      return instance.getBankID();
    }
    /**
     * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBankIDBytes() {
      return instance.getBankIDBytes();
    }
    /**
     * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBankID(
        java.lang.String value) {
      copyOnWrite();
      instance.setBankID(value);
      return this;
    }
    /**
     * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearBankID() {
      copyOnWrite();
      instance.clearBankID();
      return this;
    }
    /**
     * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBankIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBankIDBytes(value);
      return this;
    }

    /**
     * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getCustomerID() {
      return instance.getCustomerID();
    }
    /**
     * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerIDBytes() {
      return instance.getCustomerIDBytes();
    }
    /**
     * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCustomerID(
        java.lang.String value) {
      copyOnWrite();
      instance.setCustomerID(value);
      return this;
    }
    /**
     * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearCustomerID() {
      copyOnWrite();
      instance.clearCustomerID();
      return this;
    }
    /**
     * <code>string CustomerID = 2[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCustomerIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCustomerIDBytes(value);
      return this;
    }

    /**
     * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getID() {
      return instance.getID();
    }
    /**
     * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIDBytes() {
      return instance.getIDBytes();
    }
    /**
     * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setID(
        java.lang.String value) {
      copyOnWrite();
      instance.setID(value);
      return this;
    }
    /**
     * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearID() {
      copyOnWrite();
      instance.clearID();
      return this;
    }
    /**
     * <code>string ID = 3[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIDBytes(value);
      return this;
    }

    /**
     * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getCustomerNumber() {
      return instance.getCustomerNumber();
    }
    /**
     * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerNumberBytes() {
      return instance.getCustomerNumberBytes();
    }
    /**
     * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCustomerNumber(
        java.lang.String value) {
      copyOnWrite();
      instance.setCustomerNumber(value);
      return this;
    }
    /**
     * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearCustomerNumber() {
      copyOnWrite();
      instance.clearCustomerNumber();
      return this;
    }
    /**
     * <code>string CustomerNumber = 4[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCustomerNumberBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCustomerNumberBytes(value);
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasDate() {
      return instance.hasDate();
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return instance.getDate();
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDate(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setDate(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setDate(builderForValue);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeDate(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeDate(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 5[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearDate() {  copyOnWrite();
      instance.clearDate();
      return this;
    }

    /**
     * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getHow() {
      return instance.getHow();
    }
    /**
     * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHowBytes() {
      return instance.getHowBytes();
    }
    /**
     * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setHow(
        java.lang.String value) {
      copyOnWrite();
      instance.setHow(value);
      return this;
    }
    /**
     * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearHow() {
      copyOnWrite();
      instance.clearHow();
      return this;
    }
    /**
     * <code>string How = 6[json_name = "how", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setHowBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHowBytes(value);
      return this;
    }

    /**
     * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getStaffUserID() {
      return instance.getStaffUserID();
    }
    /**
     * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStaffUserIDBytes() {
      return instance.getStaffUserIDBytes();
    }
    /**
     * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStaffUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setStaffUserID(value);
      return this;
    }
    /**
     * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearStaffUserID() {
      copyOnWrite();
      instance.clearStaffUserID();
      return this;
    }
    /**
     * <code>string StaffUserID = 7[json_name = "staff_user_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStaffUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStaffUserIDBytes(value);
      return this;
    }

    /**
     * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getStaffName() {
      return instance.getStaffName();
    }
    /**
     * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStaffNameBytes() {
      return instance.getStaffNameBytes();
    }
    /**
     * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStaffName(
        java.lang.String value) {
      copyOnWrite();
      instance.setStaffName(value);
      return this;
    }
    /**
     * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearStaffName() {
      copyOnWrite();
      instance.clearStaffName();
      return this;
    }
    /**
     * <code>string StaffName = 8[json_name = "staff_name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStaffNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStaffNameBytes(value);
      return this;
    }

    /**
     * <code>bool Satisfied = 9[json_name = "satisfied", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean getSatisfied() {
      return instance.getSatisfied();
    }
    /**
     * <code>bool Satisfied = 9[json_name = "satisfied", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setSatisfied(boolean value) {
      copyOnWrite();
      instance.setSatisfied(value);
      return this;
    }
    /**
     * <code>bool Satisfied = 9[json_name = "satisfied", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearSatisfied() {
      copyOnWrite();
      instance.clearSatisfied();
      return this;
    }

    /**
     * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getComments() {
      return instance.getComments();
    }
    /**
     * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      return instance.getCommentsBytes();
    }
    /**
     * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setComments(
        java.lang.String value) {
      copyOnWrite();
      instance.setComments(value);
      return this;
    }
    /**
     * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearComments() {
      copyOnWrite();
      instance.clearComments();
      return this;
    }
    /**
     * <code>string Comments = 10[json_name = "comments", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCommentsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:kyc.Check)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.kyc.Check();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bankID_",
            "customerID_",
            "iD_",
            "customerNumber_",
            "date_",
            "how_",
            "staffUserID_",
            "staffName_",
            "satisfied_",
            "comments_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\t\u0006\u0208\u0007\u0208\b\u0208\t\u0007\n\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.kyc.Check> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.kyc.Check.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.kyc.Check>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:kyc.Check)
  private static final to.bnk.api.kyc.Check DEFAULT_INSTANCE;
  static {
    Check defaultInstance = new Check();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Check.class, defaultInstance);
  }

  public static to.bnk.api.kyc.Check getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Check> PARSER;

  public static com.google.protobuf.Parser<Check> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

