// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.atm;

public interface GetATMRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:atm.GetATMRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string ATM_ID = 1[json_name = "atm_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getATMID();
  /**
   * <code>string ATM_ID = 1[json_name = "atm_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getATMIDBytes();
}
