// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.fx;

public interface CreateFXRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fx.CreateFXRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.fx.FX FX = 1[json_name = "fx", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasFX();
  /**
   * <code>.fx.FX FX = 1[json_name = "fx", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  to.bnk.api.fx.FX getFX();
}
