// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.customer;

public interface AddSocialMediaHandleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:customer.AddSocialMediaHandleRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string CustomerID = 1[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCustomerID();
  /**
   * <code>string CustomerID = 1[json_name = "customer_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCustomerIDBytes();

  /**
   * <code>string CustomerNumber = 2[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCustomerNumber();
  /**
   * <code>string CustomerNumber = 2[json_name = "customer_number", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCustomerNumberBytes();

  /**
   * <code>string Type = 3[json_name = "type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getType();
  /**
   * <code>string Type = 3[json_name = "type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string Handle = 4[json_name = "handle", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getHandle();
  /**
   * <code>string Handle = 4[json_name = "handle", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getHandleBytes();

  /**
   * <code>.google.protobuf.Timestamp DateAdded = 5[json_name = "date_added", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasDateAdded();
  /**
   * <code>.google.protobuf.Timestamp DateAdded = 5[json_name = "date_added", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.Timestamp getDateAdded();

  /**
   * <code>.google.protobuf.Timestamp DateActivated = 6[json_name = "date_activated", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasDateActivated();
  /**
   * <code>.google.protobuf.Timestamp DateActivated = 6[json_name = "date_activated", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.Timestamp getDateActivated();
}
