// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.customer;

/**
 * Protobuf type {@code customer.FaceImage}
 */
public  final class FaceImage extends
    com.google.protobuf.GeneratedMessageLite<
        FaceImage, FaceImage.Builder> implements
    // @@protoc_insertion_point(message_implements:customer.FaceImage)
    FaceImageOrBuilder {
  private FaceImage() {
    uRL_ = "";
  }
  public static final int URL_FIELD_NUMBER = 1;
  private java.lang.String uRL_;
  /**
   * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getURL() {
    return uRL_;
  }
  /**
   * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getURLBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uRL_);
  }
  /**
   * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setURL(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    uRL_ = value;
  }
  /**
   * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearURL() {
    
    uRL_ = getDefaultInstance().getURL();
  }
  /**
   * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setURLBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    uRL_ = value.toStringUtf8();
  }

  public static final int DATE_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp date_;
  /**
   * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDate() {
    return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDate(com.google.protobuf.Timestamp value) {
    if (value == null) {
      throw new NullPointerException();
    }
    date_ = value;
    
    }
  /**
   * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDate(
      com.google.protobuf.Timestamp.Builder builderForValue) {
    date_ = builderForValue.build();
    
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDate(com.google.protobuf.Timestamp value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (date_ != null &&
        date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      date_ =
        com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
    } else {
      date_ = value;
    }
    
  }
  /**
   * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearDate() {  date_ = null;
    
  }

  public static to.bnk.api.customer.FaceImage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.customer.FaceImage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.customer.FaceImage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.customer.FaceImage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.customer.FaceImage prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code customer.FaceImage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.customer.FaceImage, Builder> implements
      // @@protoc_insertion_point(builder_implements:customer.FaceImage)
      to.bnk.api.customer.FaceImageOrBuilder {
    // Construct using to.bnk.api.customer.FaceImage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getURL() {
      return instance.getURL();
    }
    /**
     * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getURLBytes() {
      return instance.getURLBytes();
    }
    /**
     * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setURL(
        java.lang.String value) {
      copyOnWrite();
      instance.setURL(value);
      return this;
    }
    /**
     * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearURL() {
      copyOnWrite();
      instance.clearURL();
      return this;
    }
    /**
     * <code>string URL = 1[json_name = "url", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setURLBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setURLBytes(value);
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasDate() {
      return instance.hasDate();
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return instance.getDate();
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDate(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setDate(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setDate(builderForValue);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeDate(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeDate(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp Date = 2[json_name = "date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearDate() {  copyOnWrite();
      instance.clearDate();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:customer.FaceImage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.customer.FaceImage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "uRL_",
            "date_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.customer.FaceImage> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.customer.FaceImage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.customer.FaceImage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:customer.FaceImage)
  private static final to.bnk.api.customer.FaceImage DEFAULT_INSTANCE;
  static {
    FaceImage defaultInstance = new FaceImage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FaceImage.class, defaultInstance);
  }

  public static to.bnk.api.customer.FaceImage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FaceImage> PARSER;

  public static com.google.protobuf.Parser<FaceImage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

