// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.accounts;

/**
 * Protobuf type {@code accounts.CreateAccountRequest}
 */
public  final class CreateAccountRequest extends
    com.google.protobuf.GeneratedMessageLite<
        CreateAccountRequest, CreateAccountRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:accounts.CreateAccountRequest)
    CreateAccountRequestOrBuilder {
  private CreateAccountRequest() {
    accountID_ = "";
    description_ = "";
    accountRoles_ = emptyProtobufList();
    branch_ = "";
    customer_ = "";
    interestRate_ = "";
    minor_ = "";
  }
  public static final int ACCOUNTID_FIELD_NUMBER = 1;
  private java.lang.String accountID_;
  /**
   * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getAccountID() {
    return accountID_;
  }
  /**
   * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(accountID_);
  }
  /**
   * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setAccountID(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    accountID_ = value;
  }
  /**
   * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearAccountID() {
    
    accountID_ = getDefaultInstance().getAccountID();
  }
  /**
   * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setAccountIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    accountID_ = value.toStringUtf8();
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private java.lang.String description_;
  /**
   * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDescription(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    description_ = value;
  }
  /**
   * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearDescription() {
    
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    description_ = value.toStringUtf8();
  }

  public static final int ACCOUNTROLES_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<to.bnk.api.accounts.AccountRole> accountRoles_;
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.util.List<to.bnk.api.accounts.AccountRole> getAccountRolesList() {
    return accountRoles_;
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public java.util.List<? extends to.bnk.api.accounts.AccountRoleOrBuilder> 
      getAccountRolesOrBuilderList() {
    return accountRoles_;
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getAccountRolesCount() {
    return accountRoles_.size();
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.accounts.AccountRole getAccountRoles(int index) {
    return accountRoles_.get(index);
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public to.bnk.api.accounts.AccountRoleOrBuilder getAccountRolesOrBuilder(
      int index) {
    return accountRoles_.get(index);
  }
  private void ensureAccountRolesIsMutable() {
    if (!accountRoles_.isModifiable()) {
      accountRoles_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(accountRoles_);
     }
  }

  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setAccountRoles(
      int index, to.bnk.api.accounts.AccountRole value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureAccountRolesIsMutable();
    accountRoles_.set(index, value);
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setAccountRoles(
      int index, to.bnk.api.accounts.AccountRole.Builder builderForValue) {
    ensureAccountRolesIsMutable();
    accountRoles_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAccountRoles(to.bnk.api.accounts.AccountRole value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureAccountRolesIsMutable();
    accountRoles_.add(value);
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAccountRoles(
      int index, to.bnk.api.accounts.AccountRole value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureAccountRolesIsMutable();
    accountRoles_.add(index, value);
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAccountRoles(
      to.bnk.api.accounts.AccountRole.Builder builderForValue) {
    ensureAccountRolesIsMutable();
    accountRoles_.add(builderForValue.build());
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAccountRoles(
      int index, to.bnk.api.accounts.AccountRole.Builder builderForValue) {
    ensureAccountRolesIsMutable();
    accountRoles_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAllAccountRoles(
      java.lang.Iterable<? extends to.bnk.api.accounts.AccountRole> values) {
    ensureAccountRolesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, accountRoles_);
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearAccountRoles() {
    accountRoles_ = emptyProtobufList();
  }
  /**
   * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void removeAccountRoles(int index) {
    ensureAccountRolesIsMutable();
    accountRoles_.remove(index);
  }

  public static final int BRANCH_FIELD_NUMBER = 4;
  private java.lang.String branch_;
  /**
   * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getBranch() {
    return branch_;
  }
  /**
   * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBranchBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(branch_);
  }
  /**
   * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBranch(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    branch_ = value;
  }
  /**
   * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearBranch() {
    
    branch_ = getDefaultInstance().getBranch();
  }
  /**
   * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBranchBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    branch_ = value.toStringUtf8();
  }

  public static final int CUSTOMER_FIELD_NUMBER = 5;
  private java.lang.String customer_;
  /**
   * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getCustomer() {
    return customer_;
  }
  /**
   * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(customer_);
  }
  /**
   * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCustomer(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    customer_ = value;
  }
  /**
   * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearCustomer() {
    
    customer_ = getDefaultInstance().getCustomer();
  }
  /**
   * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCustomerBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    customer_ = value.toStringUtf8();
  }

  public static final int DEBITTRANSACTION_FIELD_NUMBER = 6;
  private to.bnk.api.accounts.DebitTransaction debitTransaction_;
  /**
   * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasDebitTransaction() {
    return debitTransaction_ != null;
  }
  /**
   * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.accounts.DebitTransaction getDebitTransaction() {
    return debitTransaction_ == null ? to.bnk.api.accounts.DebitTransaction.getDefaultInstance() : debitTransaction_;
  }
  /**
   * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDebitTransaction(to.bnk.api.accounts.DebitTransaction value) {
    if (value == null) {
      throw new NullPointerException();
    }
    debitTransaction_ = value;
    
    }
  /**
   * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setDebitTransaction(
      to.bnk.api.accounts.DebitTransaction.Builder builderForValue) {
    debitTransaction_ = builderForValue.build();
    
  }
  /**
   * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDebitTransaction(to.bnk.api.accounts.DebitTransaction value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (debitTransaction_ != null &&
        debitTransaction_ != to.bnk.api.accounts.DebitTransaction.getDefaultInstance()) {
      debitTransaction_ =
        to.bnk.api.accounts.DebitTransaction.newBuilder(debitTransaction_).mergeFrom(value).buildPartial();
    } else {
      debitTransaction_ = value;
    }
    
  }
  /**
   * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearDebitTransaction() {  debitTransaction_ = null;
    
  }

  public static final int INTERESTRATE_FIELD_NUMBER = 7;
  private java.lang.String interestRate_;
  /**
   * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getInterestRate() {
    return interestRate_;
  }
  /**
   * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInterestRateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(interestRate_);
  }
  /**
   * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setInterestRate(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    interestRate_ = value;
  }
  /**
   * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearInterestRate() {
    
    interestRate_ = getDefaultInstance().getInterestRate();
  }
  /**
   * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setInterestRateBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    interestRate_ = value.toStringUtf8();
  }

  public static final int MAJORTYPE_FIELD_NUMBER = 8;
  private int majorType_;
  /**
   * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getMajorTypeValue() {
    return majorType_;
  }
  /**
   * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public types.All.MajorType getMajorType() {
    types.All.MajorType result = types.All.MajorType.forNumber(majorType_);
    return result == null ? types.All.MajorType.UNRECOGNIZED : result;
  }
  /**
   * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMajorTypeValue(int value) {
      majorType_ = value;
  }
  /**
   * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMajorType(types.All.MajorType value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    majorType_ = value.getNumber();
  }
  /**
   * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearMajorType() {
    
    majorType_ = 0;
  }

  public static final int MATURITYDATE_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp maturityDate_;
  /**
   * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasMaturityDate() {
    return maturityDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getMaturityDate() {
    return maturityDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : maturityDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMaturityDate(com.google.protobuf.Timestamp value) {
    if (value == null) {
      throw new NullPointerException();
    }
    maturityDate_ = value;
    
    }
  /**
   * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMaturityDate(
      com.google.protobuf.Timestamp.Builder builderForValue) {
    maturityDate_ = builderForValue.build();
    
  }
  /**
   * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeMaturityDate(com.google.protobuf.Timestamp value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (maturityDate_ != null &&
        maturityDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      maturityDate_ =
        com.google.protobuf.Timestamp.newBuilder(maturityDate_).mergeFrom(value).buildPartial();
    } else {
      maturityDate_ = value;
    }
    
  }
  /**
   * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearMaturityDate() {  maturityDate_ = null;
    
  }

  public static final int MINOR_FIELD_NUMBER = 10;
  private java.lang.String minor_;
  /**
   * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getMinor() {
    return minor_;
  }
  /**
   * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMinorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(minor_);
  }
  /**
   * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMinor(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    minor_ = value;
  }
  /**
   * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearMinor() {
    
    minor_ = getDefaultInstance().getMinor();
  }
  /**
   * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMinorBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    minor_ = value.toStringUtf8();
  }

  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.accounts.CreateAccountRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.accounts.CreateAccountRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code accounts.CreateAccountRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.accounts.CreateAccountRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:accounts.CreateAccountRequest)
      to.bnk.api.accounts.CreateAccountRequestOrBuilder {
    // Construct using to.bnk.api.accounts.CreateAccountRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getAccountID() {
      return instance.getAccountID();
    }
    /**
     * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountIDBytes() {
      return instance.getAccountIDBytes();
    }
    /**
     * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setAccountID(
        java.lang.String value) {
      copyOnWrite();
      instance.setAccountID(value);
      return this;
    }
    /**
     * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearAccountID() {
      copyOnWrite();
      instance.clearAccountID();
      return this;
    }
    /**
     * <code>string AccountID = 1[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setAccountIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAccountIDBytes(value);
      return this;
    }

    /**
     * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string Description = 2[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.util.List<to.bnk.api.accounts.AccountRole> getAccountRolesList() {
      return java.util.Collections.unmodifiableList(
          instance.getAccountRolesList());
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getAccountRolesCount() {
      return instance.getAccountRolesCount();
    }/**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.accounts.AccountRole getAccountRoles(int index) {
      return instance.getAccountRoles(index);
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setAccountRoles(
        int index, to.bnk.api.accounts.AccountRole value) {
      copyOnWrite();
      instance.setAccountRoles(index, value);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setAccountRoles(
        int index, to.bnk.api.accounts.AccountRole.Builder builderForValue) {
      copyOnWrite();
      instance.setAccountRoles(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAccountRoles(to.bnk.api.accounts.AccountRole value) {
      copyOnWrite();
      instance.addAccountRoles(value);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAccountRoles(
        int index, to.bnk.api.accounts.AccountRole value) {
      copyOnWrite();
      instance.addAccountRoles(index, value);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAccountRoles(
        to.bnk.api.accounts.AccountRole.Builder builderForValue) {
      copyOnWrite();
      instance.addAccountRoles(builderForValue);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAccountRoles(
        int index, to.bnk.api.accounts.AccountRole.Builder builderForValue) {
      copyOnWrite();
      instance.addAccountRoles(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAllAccountRoles(
        java.lang.Iterable<? extends to.bnk.api.accounts.AccountRole> values) {
      copyOnWrite();
      instance.addAllAccountRoles(values);
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearAccountRoles() {
      copyOnWrite();
      instance.clearAccountRoles();
      return this;
    }
    /**
     * <code>repeated .accounts.AccountRole AccountRoles = 3[json_name = "account_roles", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder removeAccountRoles(int index) {
      copyOnWrite();
      instance.removeAccountRoles(index);
      return this;
    }

    /**
     * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getBranch() {
      return instance.getBranch();
    }
    /**
     * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBranchBytes() {
      return instance.getBranchBytes();
    }
    /**
     * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBranch(
        java.lang.String value) {
      copyOnWrite();
      instance.setBranch(value);
      return this;
    }
    /**
     * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearBranch() {
      copyOnWrite();
      instance.clearBranch();
      return this;
    }
    /**
     * <code>string Branch = 4[json_name = "branch", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBranchBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBranchBytes(value);
      return this;
    }

    /**
     * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getCustomer() {
      return instance.getCustomer();
    }
    /**
     * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerBytes() {
      return instance.getCustomerBytes();
    }
    /**
     * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCustomer(
        java.lang.String value) {
      copyOnWrite();
      instance.setCustomer(value);
      return this;
    }
    /**
     * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearCustomer() {
      copyOnWrite();
      instance.clearCustomer();
      return this;
    }
    /**
     * <code>string Customer = 5[json_name = "customer", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCustomerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCustomerBytes(value);
      return this;
    }

    /**
     * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasDebitTransaction() {
      return instance.hasDebitTransaction();
    }
    /**
     * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.accounts.DebitTransaction getDebitTransaction() {
      return instance.getDebitTransaction();
    }
    /**
     * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDebitTransaction(to.bnk.api.accounts.DebitTransaction value) {
      copyOnWrite();
      instance.setDebitTransaction(value);
      return this;
      }
    /**
     * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setDebitTransaction(
        to.bnk.api.accounts.DebitTransaction.Builder builderForValue) {
      copyOnWrite();
      instance.setDebitTransaction(builderForValue);
      return this;
    }
    /**
     * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeDebitTransaction(to.bnk.api.accounts.DebitTransaction value) {
      copyOnWrite();
      instance.mergeDebitTransaction(value);
      return this;
    }
    /**
     * <code>.accounts.DebitTransaction DebitTransaction = 6[json_name = "debit_transaction", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearDebitTransaction() {  copyOnWrite();
      instance.clearDebitTransaction();
      return this;
    }

    /**
     * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getInterestRate() {
      return instance.getInterestRate();
    }
    /**
     * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInterestRateBytes() {
      return instance.getInterestRateBytes();
    }
    /**
     * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setInterestRate(
        java.lang.String value) {
      copyOnWrite();
      instance.setInterestRate(value);
      return this;
    }
    /**
     * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearInterestRate() {
      copyOnWrite();
      instance.clearInterestRate();
      return this;
    }
    /**
     * <code>string InterestRate = 7[json_name = "interest_rate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setInterestRateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInterestRateBytes(value);
      return this;
    }

    /**
     * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getMajorTypeValue() {
      return instance.getMajorTypeValue();
    }
    /**
     * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMajorTypeValue(int value) {
      copyOnWrite();
      instance.setMajorTypeValue(value);
      return this;
    }
    /**
     * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public types.All.MajorType getMajorType() {
      return instance.getMajorType();
    }
    /**
     * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMajorType(types.All.MajorType value) {
      copyOnWrite();
      instance.setMajorType(value);
      return this;
    }
    /**
     * <code>.types.MajorType MajorType = 8[json_name = "major_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearMajorType() {
      copyOnWrite();
      instance.clearMajorType();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasMaturityDate() {
      return instance.hasMaturityDate();
    }
    /**
     * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getMaturityDate() {
      return instance.getMaturityDate();
    }
    /**
     * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMaturityDate(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setMaturityDate(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMaturityDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setMaturityDate(builderForValue);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeMaturityDate(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeMaturityDate(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp MaturityDate = 9[json_name = "maturity_date", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearMaturityDate() {  copyOnWrite();
      instance.clearMaturityDate();
      return this;
    }

    /**
     * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getMinor() {
      return instance.getMinor();
    }
    /**
     * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMinorBytes() {
      return instance.getMinorBytes();
    }
    /**
     * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMinor(
        java.lang.String value) {
      copyOnWrite();
      instance.setMinor(value);
      return this;
    }
    /**
     * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearMinor() {
      copyOnWrite();
      instance.clearMinor();
      return this;
    }
    /**
     * <code>string Minor = 10[json_name = "minor", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMinorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMinorBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:accounts.CreateAccountRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.accounts.CreateAccountRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "accountID_",
            "description_",
            "accountRoles_",
            to.bnk.api.accounts.AccountRole.class,
            "branch_",
            "customer_",
            "debitTransaction_",
            "interestRate_",
            "majorType_",
            "maturityDate_",
            "minor_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0001\u0000\u0001\u0208\u0002\u0208\u0003\u001b" +
              "\u0004\u0208\u0005\u0208\u0006\t\u0007\u0208\b\f\t\t\n\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.accounts.CreateAccountRequest> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.accounts.CreateAccountRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.accounts.CreateAccountRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:accounts.CreateAccountRequest)
  private static final to.bnk.api.accounts.CreateAccountRequest DEFAULT_INSTANCE;
  static {
    CreateAccountRequest defaultInstance = new CreateAccountRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateAccountRequest.class, defaultInstance);
  }

  public static to.bnk.api.accounts.CreateAccountRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateAccountRequest> PARSER;

  public static com.google.protobuf.Parser<CreateAccountRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

