// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.statements;

public interface GetStatementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statements.GetStatementRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string ID = 1[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getID();
  /**
   * <code>string ID = 1[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
