// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.transactionmetadata;

public interface GetCommentsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transactionmetadata.GetCommentsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getBankID();
  /**
   * <code>string BankID = 1[json_name = "bank_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getBankIDBytes();

  /**
   * <code>string AccountID = 2[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getAccountID();
  /**
   * <code>string AccountID = 2[json_name = "account_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getAccountIDBytes();

  /**
   * <code>string TransactionID = 3[json_name = "transaction_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getTransactionID();
  /**
   * <code>string TransactionID = 3[json_name = "transaction_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getTransactionIDBytes();
}
