// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.auth;

/**
 * Protobuf type {@code auth.CreateAccessTokenResponse}
 */
public  final class CreateAccessTokenResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CreateAccessTokenResponse, CreateAccessTokenResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:auth.CreateAccessTokenResponse)
    CreateAccessTokenResponseOrBuilder {
  private CreateAccessTokenResponse() {
    accessToken_ = "";
    tokenType_ = "";
    refreshToken_ = "";
  }
  public static final int ACCESSTOKEN_FIELD_NUMBER = 1;
  private java.lang.String accessToken_;
  /**
   * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getAccessToken() {
    return accessToken_;
  }
  /**
   * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(accessToken_);
  }
  /**
   * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setAccessToken(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    accessToken_ = value;
  }
  /**
   * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearAccessToken() {
    
    accessToken_ = getDefaultInstance().getAccessToken();
  }
  /**
   * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setAccessTokenBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    accessToken_ = value.toStringUtf8();
  }

  public static final int TOKENTYPE_FIELD_NUMBER = 2;
  private java.lang.String tokenType_;
  /**
   * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getTokenType() {
    return tokenType_;
  }
  /**
   * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tokenType_);
  }
  /**
   * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setTokenType(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    tokenType_ = value;
  }
  /**
   * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearTokenType() {
    
    tokenType_ = getDefaultInstance().getTokenType();
  }
  /**
   * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setTokenTypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    tokenType_ = value.toStringUtf8();
  }

  public static final int EXPIRESIN_FIELD_NUMBER = 3;
  private int expiresIn_;
  /**
   * <code>int32 ExpiresIn = 3[json_name = "expires_in", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getExpiresIn() {
    return expiresIn_;
  }
  /**
   * <code>int32 ExpiresIn = 3[json_name = "expires_in", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setExpiresIn(int value) {
    
    expiresIn_ = value;
  }
  /**
   * <code>int32 ExpiresIn = 3[json_name = "expires_in", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearExpiresIn() {
    
    expiresIn_ = 0;
  }

  public static final int REFRESHTOKEN_FIELD_NUMBER = 4;
  private java.lang.String refreshToken_;
  /**
   * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getRefreshToken() {
    return refreshToken_;
  }
  /**
   * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefreshTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(refreshToken_);
  }
  /**
   * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setRefreshToken(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    refreshToken_ = value;
  }
  /**
   * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearRefreshToken() {
    
    refreshToken_ = getDefaultInstance().getRefreshToken();
  }
  /**
   * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setRefreshTokenBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    refreshToken_ = value.toStringUtf8();
  }

  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.auth.CreateAccessTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.auth.CreateAccessTokenResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code auth.CreateAccessTokenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.auth.CreateAccessTokenResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:auth.CreateAccessTokenResponse)
      to.bnk.api.auth.CreateAccessTokenResponseOrBuilder {
    // Construct using to.bnk.api.auth.CreateAccessTokenResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      return instance.getAccessToken();
    }
    /**
     * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      return instance.getAccessTokenBytes();
    }
    /**
     * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setAccessToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setAccessToken(value);
      return this;
    }
    /**
     * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearAccessToken() {
      copyOnWrite();
      instance.clearAccessToken();
      return this;
    }
    /**
     * <code>string AccessToken = 1[json_name = "access_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAccessTokenBytes(value);
      return this;
    }

    /**
     * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getTokenType() {
      return instance.getTokenType();
    }
    /**
     * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenTypeBytes() {
      return instance.getTokenTypeBytes();
    }
    /**
     * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTokenType(
        java.lang.String value) {
      copyOnWrite();
      instance.setTokenType(value);
      return this;
    }
    /**
     * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearTokenType() {
      copyOnWrite();
      instance.clearTokenType();
      return this;
    }
    /**
     * <code>string TokenType = 2[json_name = "token_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTokenTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTokenTypeBytes(value);
      return this;
    }

    /**
     * <code>int32 ExpiresIn = 3[json_name = "expires_in", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getExpiresIn() {
      return instance.getExpiresIn();
    }
    /**
     * <code>int32 ExpiresIn = 3[json_name = "expires_in", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setExpiresIn(int value) {
      copyOnWrite();
      instance.setExpiresIn(value);
      return this;
    }
    /**
     * <code>int32 ExpiresIn = 3[json_name = "expires_in", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearExpiresIn() {
      copyOnWrite();
      instance.clearExpiresIn();
      return this;
    }

    /**
     * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getRefreshToken() {
      return instance.getRefreshToken();
    }
    /**
     * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      return instance.getRefreshTokenBytes();
    }
    /**
     * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setRefreshToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setRefreshToken(value);
      return this;
    }
    /**
     * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearRefreshToken() {
      copyOnWrite();
      instance.clearRefreshToken();
      return this;
    }
    /**
     * <code>string RefreshToken = 4[json_name = "refresh_token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setRefreshTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRefreshTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:auth.CreateAccessTokenResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.auth.CreateAccessTokenResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "accessToken_",
            "tokenType_",
            "expiresIn_",
            "refreshToken_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0004\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.auth.CreateAccessTokenResponse> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.auth.CreateAccessTokenResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.auth.CreateAccessTokenResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:auth.CreateAccessTokenResponse)
  private static final to.bnk.api.auth.CreateAccessTokenResponse DEFAULT_INSTANCE;
  static {
    CreateAccessTokenResponse defaultInstance = new CreateAccessTokenResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateAccessTokenResponse.class, defaultInstance);
  }

  public static to.bnk.api.auth.CreateAccessTokenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateAccessTokenResponse> PARSER;

  public static com.google.protobuf.Parser<CreateAccessTokenResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

