// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.transactions;

public interface ApprovePaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transactions.ApprovePaymentResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string AuthorizationID = 1[json_name = "authorization_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getAuthorizationID();
  /**
   * <code>string AuthorizationID = 1[json_name = "authorization_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getAuthorizationIDBytes();

  /**
   * <code>int64 SMSCode = 2[json_name = "sms_code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  long getSMSCode();
}
