// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.bank;

/**
 * Protobuf type {@code bank.CreateTransactionTypeAtBankRequest}
 */
public  final class CreateTransactionTypeAtBankRequest extends
    com.google.protobuf.GeneratedMessageLite<
        CreateTransactionTypeAtBankRequest, CreateTransactionTypeAtBankRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:bank.CreateTransactionTypeAtBankRequest)
    CreateTransactionTypeAtBankRequestOrBuilder {
  private CreateTransactionTypeAtBankRequest() {
  }
  public static final int TRANSACTIONTYPE_FIELD_NUMBER = 1;
  private to.bnk.api.bank.TransactionType transactionType_;
  /**
   * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasTransactionType() {
    return transactionType_ != null;
  }
  /**
   * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.bank.TransactionType getTransactionType() {
    return transactionType_ == null ? to.bnk.api.bank.TransactionType.getDefaultInstance() : transactionType_;
  }
  /**
   * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setTransactionType(to.bnk.api.bank.TransactionType value) {
    if (value == null) {
      throw new NullPointerException();
    }
    transactionType_ = value;
    
    }
  /**
   * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setTransactionType(
      to.bnk.api.bank.TransactionType.Builder builderForValue) {
    transactionType_ = builderForValue.build();
    
  }
  /**
   * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTransactionType(to.bnk.api.bank.TransactionType value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (transactionType_ != null &&
        transactionType_ != to.bnk.api.bank.TransactionType.getDefaultInstance()) {
      transactionType_ =
        to.bnk.api.bank.TransactionType.newBuilder(transactionType_).mergeFrom(value).buildPartial();
    } else {
      transactionType_ = value;
    }
    
  }
  /**
   * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearTransactionType() {  transactionType_ = null;
    
  }

  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.bank.CreateTransactionTypeAtBankRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code bank.CreateTransactionTypeAtBankRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.bank.CreateTransactionTypeAtBankRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:bank.CreateTransactionTypeAtBankRequest)
      to.bnk.api.bank.CreateTransactionTypeAtBankRequestOrBuilder {
    // Construct using to.bnk.api.bank.CreateTransactionTypeAtBankRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasTransactionType() {
      return instance.hasTransactionType();
    }
    /**
     * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.bank.TransactionType getTransactionType() {
      return instance.getTransactionType();
    }
    /**
     * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTransactionType(to.bnk.api.bank.TransactionType value) {
      copyOnWrite();
      instance.setTransactionType(value);
      return this;
      }
    /**
     * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTransactionType(
        to.bnk.api.bank.TransactionType.Builder builderForValue) {
      copyOnWrite();
      instance.setTransactionType(builderForValue);
      return this;
    }
    /**
     * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeTransactionType(to.bnk.api.bank.TransactionType value) {
      copyOnWrite();
      instance.mergeTransactionType(value);
      return this;
    }
    /**
     * <code>.bank.TransactionType TransactionType = 1[json_name = "transaction_type", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearTransactionType() {  copyOnWrite();
      instance.clearTransactionType();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bank.CreateTransactionTypeAtBankRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.bank.CreateTransactionTypeAtBankRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "transactionType_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.bank.CreateTransactionTypeAtBankRequest> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.bank.CreateTransactionTypeAtBankRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.bank.CreateTransactionTypeAtBankRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bank.CreateTransactionTypeAtBankRequest)
  private static final to.bnk.api.bank.CreateTransactionTypeAtBankRequest DEFAULT_INSTANCE;
  static {
    CreateTransactionTypeAtBankRequest defaultInstance = new CreateTransactionTypeAtBankRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateTransactionTypeAtBankRequest.class, defaultInstance);
  }

  public static to.bnk.api.bank.CreateTransactionTypeAtBankRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateTransactionTypeAtBankRequest> PARSER;

  public static com.google.protobuf.Parser<CreateTransactionTypeAtBankRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

