// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.bank;

public interface TransactionTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bank.TransactionType)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string ID = 1[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getID();
  /**
   * <code>string ID = 1[json_name = "id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getIDBytes();

  /**
   * <code>string BankID = 2[json_name = "bankId", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getBankID();
  /**
   * <code>string BankID = 2[json_name = "bankId", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getBankIDBytes();

  /**
   * <code>string ShortCode = 3[json_name = "short_code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getShortCode();
  /**
   * <code>string ShortCode = 3[json_name = "short_code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getShortCodeBytes();

  /**
   * <code>string Summary = 4[json_name = "summary", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getSummary();
  /**
   * <code>string Summary = 4[json_name = "summary", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getSummaryBytes();

  /**
   * <code>string Description = 5[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string Description = 5[json_name = "description", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string Currency = 6[json_name = "currency", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>string Currency = 6[json_name = "currency", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>string Amount = 7[json_name = "amount", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getAmount();
  /**
   * <code>string Amount = 7[json_name = "amount", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
