// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.bank;

/**
 * Protobuf type {@code bank.UpdateBankRequest}
 */
public  final class UpdateBankRequest extends
    com.google.protobuf.GeneratedMessageLite<
        UpdateBankRequest, UpdateBankRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:bank.UpdateBankRequest)
    UpdateBankRequestOrBuilder {
  private UpdateBankRequest() {
  }
  public static final int BANK_FIELD_NUMBER = 1;
  private to.bnk.api.bank.Bank bank_;
  /**
   * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasBank() {
    return bank_ != null;
  }
  /**
   * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.bank.Bank getBank() {
    return bank_ == null ? to.bnk.api.bank.Bank.getDefaultInstance() : bank_;
  }
  /**
   * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBank(to.bnk.api.bank.Bank value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bank_ = value;
    
    }
  /**
   * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBank(
      to.bnk.api.bank.Bank.Builder builderForValue) {
    bank_ = builderForValue.build();
    
  }
  /**
   * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBank(to.bnk.api.bank.Bank value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (bank_ != null &&
        bank_ != to.bnk.api.bank.Bank.getDefaultInstance()) {
      bank_ =
        to.bnk.api.bank.Bank.newBuilder(bank_).mergeFrom(value).buildPartial();
    } else {
      bank_ = value;
    }
    
  }
  /**
   * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearBank() {  bank_ = null;
    
  }

  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.bank.UpdateBankRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.bank.UpdateBankRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code bank.UpdateBankRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.bank.UpdateBankRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:bank.UpdateBankRequest)
      to.bnk.api.bank.UpdateBankRequestOrBuilder {
    // Construct using to.bnk.api.bank.UpdateBankRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasBank() {
      return instance.hasBank();
    }
    /**
     * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.bank.Bank getBank() {
      return instance.getBank();
    }
    /**
     * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBank(to.bnk.api.bank.Bank value) {
      copyOnWrite();
      instance.setBank(value);
      return this;
      }
    /**
     * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBank(
        to.bnk.api.bank.Bank.Builder builderForValue) {
      copyOnWrite();
      instance.setBank(builderForValue);
      return this;
    }
    /**
     * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeBank(to.bnk.api.bank.Bank value) {
      copyOnWrite();
      instance.mergeBank(value);
      return this;
    }
    /**
     * <code>.bank.Bank Bank = 1[json_name = "bank", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearBank() {  copyOnWrite();
      instance.clearBank();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bank.UpdateBankRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.bank.UpdateBankRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bank_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.bank.UpdateBankRequest> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.bank.UpdateBankRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.bank.UpdateBankRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bank.UpdateBankRequest)
  private static final to.bnk.api.bank.UpdateBankRequest DEFAULT_INSTANCE;
  static {
    UpdateBankRequest defaultInstance = new UpdateBankRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UpdateBankRequest.class, defaultInstance);
  }

  public static to.bnk.api.bank.UpdateBankRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UpdateBankRequest> PARSER;

  public static com.google.protobuf.Parser<UpdateBankRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

